### ISSUE TITLE
ADR 0001 and MISTAKES.md still assert "SDL2 never supported 10.3/10.4" - now tested and false

### ISSUE THREAD

**Issue by matthewdeaves** [matthewdeaves/old-mac-quake3#12]
Both `docs/adr/0001-the-baseline-is-the-last-sdl-1-2-commit.md` and `MISTAKES.md` carry the claim that **SDL2 never supported Mac OS X 10.3 or 10.4**. That claim was reasoned rather than tested, and it is now tested and false.

SDL2 runs on Panther with a real Cocoa backend. That is exactly what `panther-sdl2` is, and this fleet ships it: the Half-Life port links it statically on every PowerPC slice, and the Quake 1 and Quake 2 ports use it too.

The real cliff is **SDL 2.24.0**, whose Cocoa backend became ARC-only. Anything up to that point is buildable for 10.3/10.4; past it is not.

Why it matters rather than being a pedantic correction: ADR 0001 uses this claim as a load-bearing reason for pinning the baseline to the last SDL 1.2 commit. If SDL2 does work on Panther, that reason is gone, and the decision needs to rest on its other grounds (which it has) or be revisited. Leaving a false premise under a live ADR is how the wrong conclusion gets re-derived later.

To do:
- correct the claim in ADR 0001 and MISTAKES.md, naming 2.24.0 as the actual boundary
- state what the pin now rests on, since it is no longer "SDL2 cannot run there"
- check whether the same claim was copied into the Quake 1, Quake 2 or Half-Life repos

Raised from cross-repo review, 2026-08-21.

**Comment by matthewdeaves** [comment]
## Fixed, with measurement rather than a retraction

The claim was not just unmeasured, it was wrong in **both** directions. Tested
2026-08-21: same `panther-sdl2` 2.0.3 checkout, same `gcc-4.0`, same
`-arch ppc -mcpu=7400`, varying only the SDK.

| SDK | `make` | joystick / gamecontroller / haptic objects |
|---|---|---|
| 10.3.9 | **exit 2** | none |
| 10.5 | **exit 0, no errors** | all three build |

- **Too pessimistic:** SDL2 does run on 10.3/10.4. Video, audio and events all
  work, which the sister Half-Life port has been shipping on a G3 on Panther.
- **Too quiet:** joystick, `SDL_GameController` and haptic genuinely do not
  build there. SDL2's macOS joystick backend targets IOHIDManager, whose
  headers (`IOHIDBase.h`, `IOHIDDevice.h`, `IOHIDElement.h`) first appear in the
  10.5 SDK. `<IOKit/hid/IOHIDLib.h>` itself exists on 10.3.9, so the `#include`
  succeeds and it fails as `syntax error before 'IOHIDElementRef'` rather than
  as a missing file. SDL 1.2 uses the older IOCFPlugIn path, which those SDKs
  do have.

So the honest statement is **"SDL2 on 10.3/10.4 is partial, not impossible"**.

That still supports keeping the SDL 1.2 pin for this port, but on a much
narrower and now measured reason: **gamepads**, not "it would not launch".
Quake III supports controllers and the SDL 1.2 baseline is what keeps them
working on PowerPC; an SDL2 migration would trade that away unless the pre-10.5
backend were ported into the fork first.

Updated:
- `docs/adr/0001` gains a "Measured 2026-08-21" section with the A/B table, the
  header-level mechanism, and the consequence for the pin. Status line and the
  Context paragraph now point at it instead of leaving the old premise standing.
- `MISTAKES.md` records that the claim hardened for months and was wrong in both
  directions.

Cross-refs: half-life#2, quakespasm#7, quake2#9 carry the same finding from the
SDL2 side.

**Comment by matthewdeaves** [comment]
Done. All three tasks are answered, and the correction had already landed before this issue was filed, in `b666139` and the two commits before it.

**1. The claim is corrected, and 2.24.0 is not quite the boundary either.** It was tested rather than reasoned: `panther-sdl2` 2.0.3 built for `ppc` against the 10.3.9 SDK and against the 10.5 SDK, changing nothing but the SDK.

| SDK | configure | make | joystick objects |
|---|---|---|---|
| 10.3.9 | exit 0, reports joystick + haptic enabled | **exit 2** | none |
| 10.5 | exit 0 | exit 0, no errors | `SDL_sysjoystick.o`, `SDL_gamecontroller.o`, `SDL_syshaptic.o` |

So the accurate statement is narrower than either version: **on 10.3/10.4, SDL2 gives you video, audio and events, and does not give you joystick, GameController or haptic.** "Never supported" is wrong; "supported" is wrong too. ARC in 2.24.0's Cocoa backend is a real later cliff, but it is not the one that bites first.

The mechanism, since the failure is misleading: `<IOKit/hid/IOHIDLib.h>` exists in the 10.3.9 and 10.4u SDKs, so the `#include` *succeeds*. What differs is what it pulls in. On 10.5 it includes `IOHIDBase.h`, `IOHIDDevice.h` and `IOHIDElement.h`, where `IOHIDDeviceRef`, `IOHIDElementRef` and `IOHIDManagerRef` are declared. Those three headers do not exist in the old SDKs at all, so the types are undeclared and every use is a syntax error, `SDL_sysjoystick_c.h:29: error: syntax error before 'IOHIDElementRef'`. SDL 1.2's darwin backend uses the older IOCFPlugIn / `IOHIDDeviceInterface` API instead, and `IOCFPlugIn.h` is present in both old SDKs, which is why SDL 1.2 has working joysticks on Panther and Tiger and SDL2 does not.

**2. What the pin now rests on.** Not "SDL2 cannot run there". It rests on the tree, the toolchain and the per-slice arch flags being proven on this hardware, against a migration that is a large rewrite bought with no measured gain.

The one narrow live cost the ADR did record, that a move to SDL2 would trade PowerPC gamepads away, **has since been retired**. Our `panther-sdl2` fork now carries `SDL_sysjoystick_legacy.c` on the IOCFPlugIn API, and the Half-Life port ships `SDL_GameController` working on both its PowerPC slices as of v1.9.2 (matthewdeaves/old-mac-half-life-1#2). The ADR amendment says so rather than leaving a retired argument standing.

**3. Copied elsewhere? No.** Checked the Quake 1, Quake 2 and Half-Life repos: no occurrence in any of them. The claim exists only here, in ADR 0001 and `MISTAKES.md`, and both now carry the measured version.
